version: "3.5"

services :
  webapp:
       build:
         context: ./webapp
         dockerfile: Dockerfile
       networks:
         - heig2

  haproxy:
       container_name: ha
       build:
         context: ./ha
         dockerfile: Dockerfile
       ports:
         - 80:80
         - 1936:1936
         - 9999:9999
       expose:
         - 80
         - 1936
         - 9999
       networks:
         heig2:
           ipv4_address: ${HA_PROXY_IP}
networks:
    heig2:
        name: heig2
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: ${NETWORK_SUBNET}
